tests/invalid/FunctionRef_Invalid_4.whiley:14: expected lambda
    return y(123)
           ^^^^^^
